name: Trigger on "**" and "!main"

on:
  push:
    branches: 
      - "**"
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Script
        run: | 
          echo "Hello there!"
